apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: harbor
    component: redis
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk
  hostPath:
    path: "/opt/k8s/harbor/data/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-redis-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      app: harbor
      component: redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
  labels:
    app: harbor
    component: trivy
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk
  hostPath:
    path: "/opt/k8s/harbor/data/trivy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-trivy-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      app: harbor
      component: trivy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    app: harbor
    component: database
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk
  hostPath:
    path: "/opt/k8s/harbor/data/database"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-harbor-database-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      app: harbor
      component: database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
  labels:
    app: harbor
    component: jobservice
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk
  hostPath:
    path: "/opt/k8s/harbor/data/jobservice"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      app: harbor
      component: jobservice
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: harbor
    component: registry
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk
  hostPath:
    path: "/opt/k8s/harbor/data/registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      app: harbor
      component: registry

